# Generated by Django 4.2.11 on 2025-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appconfigtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='appconfigtranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='learningdomain',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='learning_domain_icons/'),
        ),
        migrations.DeleteModel(
            name='AppConfig',
        ),
        migrations.DeleteModel(
            name='AppConfigTranslation',
        ),
    ]
