# Generated by Django 4.2.11 on 2025-05-17 17:57

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDomainTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'learning domain Translation',
                'db_table': 'users_learningdomain_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='AppConfig',
        ),
        migrations.RemoveField(
            model_name='learningdomain',
            name='name',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Is Used'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Verify'), ('reset', 'Reset')], max_length=10, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_goal',
            field=models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '60 minutes')], verbose_name='Daily Goal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='discovery_source',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('playstore', 'Play Store'), ('tv', 'TV')], max_length=20, verbose_name='Discovery Source'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motivation',
            field=models.CharField(choices=[('fun', 'Fun'), ('career', 'Career'), ('education', 'Education'), ('growth', 'Growth'), ('society', 'Society')], max_length=20, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stem_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, verbose_name='STEM Level'),
        ),
        migrations.AddField(
            model_name='learningdomaintranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.learningdomain'),
        ),
        migrations.AlterUniqueTogether(
            name='learningdomaintranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
