# Generated by Django 4.2.11 on 2025-05-18 07:35

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appconfigtranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='learningdomain',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='learningdomaintranslation',
            name='name_translated',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Translated name'),
        ),
        migrations.CreateModel(
            name='LearningReasonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('tr_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Translated title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.learningreason')),
            ],
            options={
                'verbose_name': 'learning reason Translation',
                'db_table': 'users_learningreason_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
