# Generated by Django 4.2.11 on 2025-05-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_learningreason_alter_learningdomain_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='motivation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_motivation', to='users.learningreason'),
        ),
    ]
