# Generated by Django 4.2.11 on 2025-05-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_motivation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningReason',
            new_name='LearningMotivation',
        ),
        migrations.RenameModel(
            old_name='LearningReasonTranslation',
            new_name='LearningMotivationTranslation',
        ),
        migrations.AlterModelOptions(
            name='learningmotivationtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'learning motivation Translation'},
        ),
        migrations.AlterModelTable(
            name='learningmotivationtranslation',
            table='users_learningmotivation_translation',
        ),
    ]
