# Generated by Django 4.2.11 on 2025-05-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_learningreason_learningmotivation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningdomain',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_goal',
            field=models.IntegerField(choices=[(1, '5'), (2, '10'), (3, '15'), (4, '30'), (5, '60')], verbose_name='Daily Goal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='discovery_source',
            field=models.CharField(choices=[(1, 'Google'), (2, 'Facebook'), (3, 'TikTok'), (4, 'Play Store'), (5, 'TV')], max_length=20, verbose_name='Discovery Source'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stem_level',
            field=models.CharField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (2, 'Advanced')], max_length=20, verbose_name='STEM Level'),
        ),
    ]
