# Generated by Django 4.2.11 on 2025-05-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_name_learningdomain_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discovery_source',
            field=models.CharField(max_length=20, verbose_name='Discovery Source'),
        ),
    ]
