# Generated by Django 4.2.11 on 2025-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_discovery_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discovery_source',
            field=models.CharField(choices=[(1, 'Google'), (2, 'Facebook'), (3, 'TikTok'), (4, 'Play Store'), (5, 'TV')], max_length=20, verbose_name='Discovery Source'),
        ),
    ]
