# Generated by Django 4.2.11 on 2025-05-18 17:05

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_discovery_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPeriodTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('period_value', models.IntegerField(default=1, verbose_name='Period Value')),
                ('period_unit', models.CharField(choices=[('daily', 'Day'), ('weekly', 'Week'), ('monthly', 'Month'), ('yearly', 'Year')], default='daily', max_length=10, verbose_name='Period Unit')),
                ('complement', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LearningPeriodTargetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('tr_complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Translated title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.learningperiodtarget')),
            ],
            options={
                'verbose_name': 'learning period target Translation',
                'db_table': 'users_learningperiodtarget_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
