# Generated by Django 4.2.11 on 2025-05-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_learningperiodtarget_learningperiodtargettranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='discovery_source',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stem_level',
        ),
        migrations.AlterField(
            model_name='learningperiodtarget',
            name='complement',
            field=models.CharField(blank=True, help_text='Great, Awesome, etc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learningperiodtargettranslation',
            name='tr_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Translated complement'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_goal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_goal', to='users.learningperiodtarget'),
        ),
    ]
