# Generated by Django 4.2.11 on 2025-05-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprofile_discovery_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningperiodtarget',
            old_name='period_value',
            new_name='repeat_count',
        ),
    ]
