# Generated by Django 4.2.11 on 2025-05-18 18:06

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_period_value_learningperiodtarget_repeat_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningperiodtarget',
            name='complement',
        ),
        migrations.AlterField(
            model_name='learningperiodtargettranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complement', to='users.learningperiodtarget'),
        ),
    ]
