# Generated by Django 4.2.11 on 2025-05-18 18:08

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_learningperiodtarget_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningperiodtarget',
            name='complement',
            field=models.CharField(blank=True, help_text='Great, Awesome, etc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learningperiodtargettranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.learningperiodtarget'),
        ),
    ]
