# Generated by Django 4.2.11 on 2025-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appconfigtranslation',
            old_name='value',
            new_name='value_translated',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
