# Generated by Django 4.2.11 on 2025-05-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='custom_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
